[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
